{ MENU

{ GLOBAL

{ ARRAY TABLE - STRINGS (VEHICLE CONTROL)

[0] - (HOLD)
[1]  - (TAP)
[2] - (PRESS)
[3] - (HOLD/TAP)
[4] - ENTER/EXIT THE VEHICLE
[5] - USE NITROUS
[6] - USE HANDBRAKE
[7] - SWITCH RADIO
[8] - TOGGLE BLINKERS
[9] - TURN ON/OFF CAR ENGINE
[10] - TOGGLE CAMERA
[11] - RESPAWN (WHEN CRASHED)
[12] - PRESS
[13] - OR
[14] - TO EXIT TO MAIN MENU
[15] - MOVE LEFT
[16] - MOVE RIGHT


CUSTOM STRING: [0 - TEXT FROM INDEX] [1 - INPUT BINDING STRING] [2 - TEXT FROM INDEX]

}

{ ARRAY TABLE - STRINGS  (MAIN MENU)

[0] - GAMEMODE TITLE
[1] - GAMEMODE CODE AND PACK
[2] - AUTHORS
[3] - VEHICLE CONTROLS
[4] - PLAY
[5] - SELECT CAR
[6] - TUNE CAR
[7] - MODE SETTINGS
[8] - EXIT TO LOBBY


}

{ ARRAY TABLE - STRINGS (TUNE CAR )

[0] - SELECT RADIOSTATION:
[1] - START OUTSIDE THE CAR?
[2] - NITROUS:
[3] - STARTING NITROUS PERCENT: 
[4] - NITROUS POWER MULTIPLIER: 
[5] - EXIT TO MAIN MENU

}

{ ARRAY TABLE - STRINGS (MODE SETTINGS)

[0] - CURRENT MODE:
[1] - NUMBER OF LAPS:
[2] - IS REVERSED?:
[3] - SCORE CONDITION:
[4] - SCORE THRESHOLD:
[5] - EXIT TO MAIN MENU

}

}

{ #MAIN MENU

{ ARRAY TABLE -  MIN CLAMP VALUES (MAIN MENU)

[0] - VEHICLE CONTROLS - (NULL)
[1] - PLAY - (NULL)
[2] - SELECT CAR - FIRST INDEX OF CAR LIST
[3] - TUNE CAR - (NULL)
[4] - MODE SETTINGS - (NULL)
[5] - CURRENT MAP - (NULL)

}

{ ARRAY TABLE - MAX CLAMP VALUES (MAIN MENU)

[0] - VEHICLE CONTROLS - (NULL)
[1] - PLAY - (NULL)
[2] - SELECT CAR - LAST INDEX OF CAR LIST
[3] - TUNE CAR - (NULL)
[4] - MODE SETTINGS - (NULL)
[5] - CURRENT MAP - (NULL)

}

{ ARRAY TABLE - VALUE TYPE LIST (MAIN MENU)

[0] - VEHICLE CONTROLS - BUTTON
[1] - PLAY  - BUTTON
[2] - SELECT CAR - FLOAT
[3] - TUNE CAR  - BUTTON
[4] - MODE SETTINGS - BUTTON
[5] - CURRENT MAP - BUTTON

}

{ CURRENT STORED VARIABLES - (MAIN MENU)

[0] - CURRENT MENU OPTION
[1] - NULL
[2] - CURRENT CAR

}

}

{ #TUNE CAR

{ ARRAY TABLE - MIN CLAMP VALUES (TUNE CAR)

[0] - SELECT RADIOSTATION: - FIRST INDEX OF RADIO LIST
[1] - START OUTSIDE THE CAR?
[2] - IS NITROUS ENABLED?
[3] - REGENS WHEN UNUSED?
[4] - REGENS WHEN PERFORMING STUNTS?
[5] - STARTING NITROUS PERCENT: 
[6] - NITROUS POWER MULTIPLIER: 

}

{ ARRAY TABLE - MAX CLAMP VALUES (TUNE CAR)

[0] - SELECT RADIOSTATION: - LAST INDEX OF RADIO LIST
[1] - START OUTSIDE THE CAR? - TRUE
[2] - IS NITROUS ENABLED?  - TRUE
[3] - REGENS WHEN UNUSED?  - TRUE
[4] - REGENS WHEN PERFORMING STUNTS?  - TRUE
[5] - STARTING NITROUS PERCENT: 100
[6] - NITROUS POWER MULTIPLIER: X10

}

{ ARRAY TABLE - VALUE TYPE LIST (TUNE CAR )

[0] - START OUTSIDE OF THE CAR?  - BOOLEAN
[1] - IS NITROUS ENABLED? - BOOLEAN
[2] - REGENS WHEN UNUSED? - BOOLEAN
[3] - REGENS WHEN PERFORMING STUNTS? - BOOLEAN
[4] - STARTING NITROUS PERCENT: - FLOAT
[5] - NITROUS POWER MULTIPLIER: - FLOAT
[6] - EXIT TO MAIN MENU - BUTTON

}

{ ARRAY TABLE - BUTTON HEADER LIST (TUNE CAR)

[0] - VALUE IN ARRAY, GLOBAL VARIABLE (VAR_ARRAY_STRING_MENU_LIST) [6] - CURRENT MENU TITLE: TUNE CAR
[1] - VALUE IN ARRAY, GLOBAL VARIABLE (VAR_ARRAY_STRING_TUNE_LIST) [0] - SELECT RADIOSTATION
[2] - VALUE IN ARRAY, GLOBAL VARIABLE (VAR_ARRAY_STRING_TUNE_LIST) [1] - START OUTSIDE OF THE CAR?
[4] - VALUE IN ARRAY, GLOBAL VARIABLE (VAR_ARRAY_STRING_TUNE_LIST) [3] - NITROUS
[6] - VALUE IN ARRAY, GLOBAL VARIABLE (VAR_ARRAY_STRING_TUNE_LIST) [4] - STARTING NITROUS PERCENT
[7] - VALUE IN ARRAY, GLOBAL VARIABLE (VAR_ARRAY_STRING_TUNE_LIST) [5] - NITROUS POWER MULTIPLIER

}

{ ARRAY TABLE - SUB-BUTTON HEADER LIST (TUNE CAR)




}

{ CURRENT STORED VARIABLES - (TUNE CAR MENU)

[0] - SELECT RADIOSTATION: 
[1] - START OUTSIDE OF THE CAR?:
[2] - NITROUS:
[3] - STARTING NITROUS PERCENT:
[4] - NITROUS POWER MULTIPLIER: 

}

}

{ #MODE SETTINGS

{ ARRAY TABLE - MIN CLAMP VALUES (MODE SETTINGS)

[0] - CURRENT MODE: - FIRST INDEX OF MODE NAME LIST
[1] - NUMBER OF LAPS:
[2] - IS REVERSED?:
[3] - SCORE CONDITION:
[4] - SCORE THRESHOLD:
[5] - EXIT TO MAIN MENU - (NULL)

}

{ ARRAY TABLE - MAX CLAMP VALUES (MODE SETTINGS)

[0] - CURRENT MODE: - LAST INDEX OF MODE NAME LIST
[1] - NUMBER OF LAPS:
[2] - IS REVERSED?:
[3] - SCORE CONDITION:
[4] - SCORE THRESHOLD:
[5] - EXIT TO MAIN MENU - (NULL)

}

{ ARRAY TABLE - VALUE TYPE LIST (MODE SETTINGS)

[0] - CURRENT MODE - FLOAT
[1] - NUMBER OF LAPS - FLOAT
[2] - IS REVERSED? - BOOLEAN
[3] - SCORE CONDITION - TOGGLE
[4] - SCORE THRESHOLD - SPECIAL FLOAT
[5] - EXIT TO MAIN MENU - BUTTON

}

{ CURRENT STORED VARIABLES - (MODE SETTINGS)

[0] - CURRENT MODE:
[1] - NUMBER OF LAPS:
[2] - IS REVERSED?:
[3] - SCORE CONDITION:
[4] - SCORE THRESHOLD:
[5] - CHECKPOINT RADIUS: 
[6] - DYNAMITE TRIAL - START WITH REMAINING TIME:
[7] - DYNAMITE TRIAL - TIME EARNED VIA CHECKPOINT:

}


}




{ ARRAY TABLE - ACTIVE BUTTON FEEDBACK COLOR

Ranged from setted FIRST INDEX VALUE to LAST INDEX VALUE in "VAR_ARRAY_CURR_MENU_NAV_LIMITS".

}

{ ARRAY TABLE - INTERNAL STORAGE VARIABLE


#MAIN MENU

[0] - CURRENT MENU OPTION
[1] - CURRENT CAR: [0] 	AVENTADOR/SIÁN

#TUNE CAR

[2] - SELECT RADIOSTATION
[3] - START OUTSIDE THE CAR?
[4] - NITROUS: [ENABLED (REGENERATES VIA STUNTS)]
[5] - STARTING NITROUS PERCENT:
[6] - NITROUS POWER MULTIPLIER: [X2]

#MODE SETTINGS

[7] - CURRENT MODE: [0] FREE-DRIVE

#CHECKPOINT MODE
[8] - NUMBER OF LAPS: [3]
[9] - IS REVERSED?: [FALSE]
[10] - SCORE CONDITION: [OFF]
[11] - SCORE THRESHOLD: [10000]
[12] - CHECKPOINT RADIUS: 

#DYNAMITE TRIAL
[13] - REMAINING TIME AT THE START: [30]
[14] - TIME EARNED VIA CHECKPOINT: [10]

}

}

{ GAME IN PROGRESS

{ GLOBAL

{ ARRAY TABLE - IN-GAME STRINGS

[0] - VEHICLE ENTERED
[1] - VEHICLE EXITED
[2] - ENGINE ON
[3] - ENGINE IS OFF! PRESS
[4] - AND
[5] - TO TURN IT ON!
[6] - PRESS
[7] - TO ENTER THE VEHICLE
[8] - TO RESPAWN
[9] - TO RESTART
[10] - You crashed!
[11] - Respawning...
[12] - Restarting...
[13] - RADIOSTATION:
[14] - SCORE:
[15] - LAP:
[16] - FINAL LAP!
[17] - FINISH!

}

{ ARRAY TABLE - STUNT NAMES STRINGS

[0] - DRIFT
[1]  - E-DRIFT
[2] - AIR

}

{ ARRAY TABLE - STUNT LEVELS STRINGS

[0] - <NAMELESS> (LEVEL 1)
[1] - GREAT (LEVEL 2)
[2] - AWESOME (LEVEL 3)
[3] - SICK (LEVEL 4)
[4] - ULTIMATE (LEVEL 5)
[5] - INHUMAN (LEVEL 6)

}

}

{ CAR BUILDING

{ ARRAY TABLE - CAR BUILDING

[0] - START POSITION
[1]  - END POSITION


}

{ ARRAY TABLE - CAR CUSTOM COLOR VARIABLE

[0] - FRONT BUMPER COLOR (RED)
[1] - FRONT BUMPER COLOR (GREEN)
[2] - FRONT BUMPER COLOR (BLUE)

[3] - HOOD COLOR (RED)
[4] - HOOD COLOR (GREEN)
[5] - HOOD COLOR (BLUE)

[6] - BODY COLOR (RED)
[7] - BODY COLOR (GREEN)
[8] - BODY COLOR (BLUE)

[9] - TRUNK COLOR  (RED)
[10] - TRUNK COLOR  (GREEN)
[11] - TRUNK COLOR  (BLUE)

[12] - REAR BUMPER COLOR (RED)
[13] - REAR BUMPER COLOR (GREEN)
[14] - REAR BUMPER COLOR (BLUE)

[15] - HEADLIGHTS COLOR (RED)
[16] - HEADLIGHTS COLOR (GREEN)
[17] - HEADLIGHTS COLOR (BLUE)

[18] - REAR LIGHTS COLOR (RED)
[19] - REAR LIGHTS COLOR (GREEN)
[20] - REAR LIGHTS COLOR (BLUE)

[21] - NITROUS COLOR (RED)
[22] - NITROUS COLOR (GREEN)
[23] - NITROUS COLOR (BLUE)

}

{ ARRAY TABLE - CAR DEFAULT COLOR VARIABLE

[0] - FRONT BUMPER COLOR
[1] - HOOD COLOR
[2] - BODY COLOR
[3] - TRUNK COLOR
[4] - REAR BUMPER COLOR

}

{ ARRAY TABLE - CAR DEFAULT LIGHTS VARIABLE


[0] - NITROUS COLOR
[1] - HEADLIGHTS COLOR
[2] - REAR LIGHTS COLOR
[3] - REAR BLINKER COLOR

}

}

{ CAR CUSTOMIZATION

{ ARRAY TABLE - CAR CUSTOMIZATION STORED

[0] - FRONT BUMPER COLOR
[1] - HOOD COLOR
[2] - BODY COLOR
[3] - TRUNK COLOR
[4] - REAR BUMPER COLOR

}

{ ARRAY TABLE - LIGHT CUSTOMIZATION STORED

[0] - NITROUS COLOR
[1] - HEADLIGHTS COLOR
[2] - REAR LIGHTS COLOR
[3] - BLINKER COLOR

}

}

{ VEHICLE

{ ARRAY TABLE - VEHICLE MECHANICS

[0] - ACCELERATION - DESTINATION (RECEIVER)
[1] - ACCELERATION - RATE (RECEIVER)

[2] - MAIN STEERING ACCELERATION - DESTINATION (RECEIVER)
[3] - LEFT STEERING ACCELERATION - DESTINATION (RECEIVER)
[4] - RIGHT STEERING ACCELERATION - DESTINATION (RECEIVER)

[5] -  MAIN STEERING ACCELERATION - RATE (RECEIVER)

}

{ ARRAY TABLE - VEHICLE MECHANICS VALUES

[0] - MAIN STEERING ACCELERATION - DESTINATION (REGULAR)
[1] - MAIN STEERING ACCELERATION - DESTINATION (HANDBRAKING)

[2] - MAIN STEERING ACCELERATION - RATE (REGULAR)
[3] - MAIN STEERING ACCELERATION - RATE (BOOSTED)
[4] - MAIN STEERING ACCELERATION - RATE (RELEASED)

}

{ ARRAY TABLE - NITROUS MECHANICS

[0] - NITROUS DESTINATION
[1] - NITROUS CURRENT DEPLETION / REGEN RATE
[2] - NITROUS MAX TANK
[3] - NITROUS STARTING TANK
[4] - NITROUS POWER MULTIPLIER
[5] - NITROUS DEPLETION RATE (REGULAR)
[6] - NITROUS DEPLETION RATE (DRIFTING)
[7] - NITROUS DEPLETION RATE (AIRBORNE)
[8] - NITROUS REGEN RATE (SELF-REPLENISH)
[9] - NITROUS REGEN RATE (DRIFTING)
[10] - NITROUS REGEN RATE (AIRBORNE)

}

{ ARRAY TABLE - CAMERA MECHANICS

[0] - CAMERA FOCUS
[1] - CAMERA Y POSITION
[2] - CAMERA Z POSITION
[3] - CAMERA DIRECTION/DISTANCE
[4] - CAMERA BLEND SPEED

[5] - CAMERA VERTICAL ANGLE
[6] - CAMERA TYPE STRING
[7] - CAMERA TYPE VALUE




#NOTE for [0] = CAMERA DIRECTION VALUE

(-6 = Front)
(6 = Back)
(Higher/Lesser Value means how Close/Far the Chase/Free Camera will be)


}

{ ARRAY TABLE - CAR FUNCTION MECHANICS

[0] - CAR FUNCTION TRIGGER COOLDOWN
[1] - ENGINE STATUS
[2] - CURRENT RADIOSTATION
[3] - CURRENT RADIOSTATION COLOR
[4] - LEFT BLINKER TRIGGER
[5] - RIGHT BLINKER TRIGGER


}

{ ARRAY TABLE - PLAYER FEEDBACKS

[0] - NITROUS SOUND START/END VOLUME - 200
[1] - NITROUS SOUND LOOP VOLUME - 0
[2] - NITROUS CURRENT COLOR - BLACK
[3] - NITROUS HUD CURRENT COLOR - BLACK
[4] - HEADLIGHTS CURRENT COLOR - WHITE
[5] - LEFT REAR LIGHT CURRENT COLOR - BLACK
[6] - RIGHT REAR LIGHT CURRENT COLOR - BLACK

}

{ ARRAY TABLE - CAR NAVIGATION 

[0] - ACCELERATION STRING
[1] - STEERING STRING
[2] - NITROUS TRIGGERED
[3] - HANDBRAKE PULLED
[4] - FUNCTIONS
[5] - LOOK BACK TRIGGER
[6] - ENGINE STATUS
[7] - STEERING ENABLED
[8] - BLINKERS ENABLED
[9] - LEFT BLINKER ON
[10] - RIGHT BLINKER ON

}

}

}
